### PR TITLE
fix(event): ListenerSignatureVisitor accept more than two type wrongly

### LINKED ISSUE #3693: Can't register event such as `ChangeEntityEquipmentEvent event, @Last Locatable locatable`
### Affected Product(s)

SpongeVanilla

### Version

759075625270c45a6895b2c3250ebe831b62afb5

### Operating System

Win

### Java Version

17.0.3 by JetBrains s.r.o.

### Plugins/Mods

```shell
custom
```

### Describe the bug

When registering `ChangeEntityEquipmentEvent` with `(final ChangeEntityEquipmentEvent event,@Getter("transaction") Transaction<ItemStackSnapshot> transaction)`. Sponge will throw something like `Incorrect number of type arguments for [interface org.spongepowered.api.event.entity.ChangeEntityEquipmentEvent]: expected 0, but got 1`

Caused by `ListenerSignatureVisitor` accept more than two type wrongly

### Link to logs

_No response_

### PR DESCRIPTION
**Pull request by SettingDust**
fix #3693

### CODE REVIEW

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 1]
```diff
@@ -53,6 +39,19 @@
...
+import org.objectweb.asm.ClassReader;
+import org.objectweb.asm.ClassVisitor;
+import org.objectweb.asm.Label;
+import org.objectweb.asm.MethodVisitor;
+import org.objectweb.asm.Opcodes;
+import org.objectweb.asm.Type;
+import org.objectweb.asm.signature.SignatureReader;
+import org.objectweb.asm.signature.SignatureVisitor;
+import org.spongepowered.api.event.Listener;
+import org.spongepowered.api.event.Order;
```
Comment (gabizou) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java:41]: Mind just merging this commit with the last commit? No sense in keeping the extra commit for style fixes.
