### PR TITLE
Force auto-populate into global config

### LINKED ISSUE #2076: auto-populate broken since config rework
This issue was originally submitted by @PorPit in [SpongePowered/SpongeForge#2393](https://github.com/SpongePowered/SpongeForge/issues/2393).
___
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3409
- Forge version: forge-1.12.2-14.23.4.2705
- Java version: 1.8
- Operating System: windows server 2012

- Plugins/Mods:
Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActionBroadcaster, CMD Item, CarrotShop, CrazyFeetSponge, EconomyLite, EpicBanItem, GriefPrevention, LinkMe, LuckPerms, MCRMB, McrmbCommand, Nucleus, PixelVip, PlaceholderAPI, PlotSquared, ProjectCore, SpongyCord, StackBan, StopUnloadWorld, Twenty Ticks, VirtualChest, VirtualTool, World Polisher
Mods (44): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Solar Panels, Applied Energistics 2, Baubles, Better Records, Botania, CraftTweaker JEI Support, CraftTweaker2, CraftTweakerSync, CreativeCore, CreativeCoreDummy, CustomNPCs, Extra Planets, FTB Utilities, FTBLib, FoamFix, FoamFixCore, Galacticraft Core, Galacticraft Planets, Immersive Engineering, Immersive Tech, IndustrialCraft 2, Iron Chest, Just Enough Items, MJRLegendsLib, MTLib, Mekanism, MekanismGenerators, Micdoodle8 Core, MineCamera, MineCameraDummy, Mod Tweaker, OnlinePictureFrame, Pam's HarvestCraft, Shadowfacts' Forgelin, Thaumcraft, Wireless Crafting Terminal 2, WorldEdit, p455w0rd's Library

**Issue Description**
when i use the new sponge version（3361 or 3409） 
set the  global config  "tileentity-activation=true" and "auto-populate=true" and restart server
config does not add any tileentities to default settings
but when i use sponge 7.1.0-BETA-3206
the default settings can be generated normally

### PR DESCRIPTION
**Pull request by phit**
Fixes #2076 

still gonna use the value of auto-populate per world, as you may want to disable things from one dimensions being added to the config for whatever reason

~~still need to figure out how to handle collision configs~~

### CODE REVIEW

File: src/main/java/org/spongepowered/common/mixin/entitycollisions/MixinBlock_Collisions.java [hunk 1]
```diff
@@ -82,7 +83,8 @@ public boolean requiresCollisionsCacheRefresh() {
     @Override
     public void initializeCollisionState(World worldIn) {
         SpongeConfig<? extends GeneralConfigBase> activeConfig = ((IMixinWorldServer) worldIn).getActiveConfig();
-        EntityCollisionCategory collisionCat = activeConfig.getConfig().getEntityCollisionCategory();
+        SpongeConfig<? extends GeneralConfigBase> globalConfig = SpongeImpl.getGlobalConfig();
+        EntityCollisionCategory collisionCat = globalConfig.getConfig().getEntityCollisionCategory();
         this.setMaxCollisions(collisionCat.getMaxEntitiesWithinAABB());
```
Comment (lucko) [inline src/main/java/org/spongepowered/common/mixin/entitycollisions/MixinBlock_Collisions.java]: The value should still be read from the `activeConfig` instance, to allow for per-world overrides.

File: src/main/java/org/spongepowered/common/mixin/entitycollisions/MixinEntity_Collisions.java [hunk 2]
```diff
@@ -114,15 +115,16 @@ public void setModDataId(String id) {
     @Override
     public void initializeCollisionState(World worldObj) {
         SpongeConfig<? extends GeneralConfigBase> activeConfig = ((IMixinWorldServer) worldObj).getActiveConfig();
-        EntityCollisionCategory collisionCat = activeConfig.getConfig().getEntityCollisionCategory();
+        SpongeConfig<? extends GeneralConfigBase> globalConfig = SpongeImpl.getGlobalConfig();
+        EntityCollisionCategory collisionCat = globalConfig.getConfig().getEntityCollisionCategory();
         this.maxCollisions = collisionCat.getMaxEntitiesWithinAABB();
```
Comment (lucko) [inline src/main/java/org/spongepowered/common/mixin/entitycollisions/MixinEntity_Collisions.java]: The value should still be read from the `activeConfig` instance, to allow for per-world overrides.

File: src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java [hunk 3]
```diff
@@ -443,7 +444,7 @@ public static void addEntityToConfig(World world, SpongeEntityType type, byte ac
         entityType = EntityActivationRange.activationTypeMappings.get(activationType);
         final String entityModId = type.getModId().toLowerCase();
         final String entityId = type.getName().toLowerCase();
-        EntityActivationRangeCategory activationCategory = config.getConfig().getEntityActivationRange();
+        EntityActivationRangeCategory activationCategory = globalConfig.getConfig().getEntityActivationRange();
         EntityActivationModCategory entityMod = activationCategory.getModList().get(entityModId);
         Integer defaultActivationRange = activationCategory.getDefaultRanges().get(entityType);
```
Comment (lucko) [inline src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java:449]: The value should still be read from the `config` instance, to allow for per-world overrides.

File: src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java [hunk 4]
```diff
@@ -227,13 +227,14 @@ public static boolean checkIfActive(TileEntity tileEntity) {
...
+        if (config == null || globalConfig == null || type == null || !config.getConfig().getTileEntityActivationRange().autoPopulateData()) {
             return;
         }
 
         boolean requiresSave = false;
         final String tileModId = type.getModId().toLowerCase();
-        TileEntityActivationCategory activationCategory = config.getConfig().getTileEntityActivationRange();
+        TileEntityActivationCategory activationCategory = globalConfig.getConfig().getTileEntityActivationRange();
         TileEntityActivationModCategory tileEntityMod = activationCategory.getModList().get(tileModId);
         int defaultRange = activationCategory.getDefaultBlockRange();
```
Comment (lucko) [inline src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java:239]: Same as other places, the value should be read from the "active" `config` instance.

**Review by lucko — CHANGES_REQUESTED** [review]
Looks ok, other than that the value reads should still be made from the active (world/dim specific) config instances, other than global.

File: src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java (hunk 3 above)
Comment (lucko) [reply src/main/java/org/spongepowered/common/mixin/plugin/entityactivation/EntityActivationRange.java:449]: Nevermind, doesn't apply here.

File: src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java (hunk 4 above)
Comment (lucko) [reply src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java:239]: Nevermind, doesn't apply here.

**Comment by Shybella** [comment]
is this getting added?
