### PR TITLE
Fixed Skull's not looking up Skin Data if both the UUID and Name is present. Fixes #1013

### LINKED ISSUE #1013: Setting RepresentedPlayerData on a Skull ItemStack does not set the skin.
The following code is the test case. It sets the Owner tag on the Skull, but it doesn't set the skin. The default skin is still used.

```
SkullData data = Sponge.getGame().getDataManager().getManipulatorBuilder(SkullData.class).get().create();
data.set(Keys.SKULL_TYPE, SkullTypes.PLAYER);
ItemStack stack = Sponge.getGame().getRegistry().createBuilder(ItemStack.Builder.class).itemType(ItemTypes.SKULL).itemData(data).build();
RepresentedPlayerData skinData = Sponge.getGame().getDataManager().getManipulatorBuilder(RepresentedPlayerData.class).get().create();
skinData.set(Keys.REPRESENTED_PLAYER, GameProfile.of(UUID.fromString("4c38ed11-596a-4fd4-ab1d-26f386c1cbac"), "MHF_Blaze"));
stack.offer(skinData);
```

### PR DESCRIPTION
**Pull request by me4502**
This fixes the issue #1013 by looking up the texture data even if both the UUID and Name are present.

Whilst I could have put an or in place in the previous lookup, the most 'proper' way is to lookup via UUID.

### CODE REVIEW

File: src/main/java/org/spongepowered/common/data/processor/common/SkullUtils.java [hunk 1]
```diff
@@ -144,6 +144,14 @@ public static boolean setProfile(ItemStack skull, @Nullable GameProfile profile)
                 SpongeImpl.getLogger().debug("Exception while trying to resolve GameProfile: ", e);
                 return null;
             }
+        } else if (!profile.getPropertyMap().containsKey("textures")) {
+            final CompletableFuture<GameProfile> future = resolver.get(profile.getUniqueId());
```
Comment (kashike) [inline src/main/java/org/spongepowered/common/data/processor/common/SkullUtils.java]: Use `fill(profile.getUniqueId())`

Comment (me4502) [reply src/main/java/org/spongepowered/common/data/processor/common/SkullUtils.java]: Ah, good point. I'll fix tomorrow morning.

**Review by kashike — APPROVED** [review]
