### PR TITLE
fix(vanilla): PluginPackResources#getResources not working

### LINKED ISSUE #3677: `PluginPackResources#getResources` not working
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.0.0-RC1118

### Operating System

Windows

### Java Version

11.0.14.1 by Microsoft

### Plugins/Mods

```shell
Developing
```

### Describe the bug

- [x] Resolve namespace twice https://github.com/SpongePowered/Sponge/blob/api-8/vanilla/src/main/java/org/spongepowered/vanilla/server/packs/PluginPackResources.java#L92=
	The path will look like `data\plugin-foo\plugin-foo`. But it should be `data\plugin-foo`
- [x] Output always the input path instead of the files https://github.com/SpongePowered/Sponge/blob/api-8/vanilla/src/main/java/org/spongepowered/vanilla/server/packs/PluginPackResources.java#L96=

### Link to logs

_No response_

### PR DESCRIPTION
**Pull request by SettingDust**
fix #3677
Dupe resolve of namespace
Filter files
Output always input path

### CODE REVIEW

File: vanilla/src/main/java/org/spongepowered/vanilla/server/packs/PluginPackResources.java [hunk 1]
```diff
@@ -89,12 +89,15 @@ public Collection<ResourceLocation> getResources(final PackType type, final Stri
...
             final Path root = this.typeRoot(type);
-            return Files.walk(root.resolve(namespace).resolve(namespace), depth)
-                .filter(s -> !s.getFileName().toString().endsWith(".mcmeta"))
-                .map(Object::toString)
-                .filter(fileNameValidator)
-                .map(s -> new ResourceLocation(namespace, path))
-                .collect(Collectors.toList());
+            final Path namespaceDir = root.resolve(namespace);
+            return Files.walk(namespaceDir, depth)
+                    .filter(Files::isRegularFile)
```
Comment (SettingDust) [inline vanilla/src/main/java/org/spongepowered/vanilla/server/packs/PluginPackResources.java:94]: The `FilePackResources` from Minecraft looks like below codes, so I filter files:
```java
while(var3.hasMoreElements()) {
    ZipEntry var7 = var3.nextElement();
    if (!var7.isDirectory()) {
        String var8 = var7.getName();
        if (!var8.endsWith(".mcmeta") && var8.startsWith(var6)) {
            String var9 = var8.substring(var5.length());
            String[] var10 = var9.split("/");
            if (var10.length >= param3 + 1 && param4.test(var10[var10.length - 1])) {
                var4.add(new ResourceLocation(param1, var9));
            }
        }
    }
}
```
