### PR TITLE
Wrap Event Listener Registration

### LINKED ISSUE #3589: Server crash with Randompatches
**I am currently running**

- SpongeForge version: 1.16.5-36.2.5-8.0.0-RC1036
- SpongeVanilla version: N/A
- Java version: 11.0.13
- Operating System: Windows 10

- Plugins/Mods:

Randompatches 2.4.4

**Issue Description**

Crash on startup, full log also attached. This error doesn't occur without Spongeforge present, despite the reference to a client class.
```
[14Jan.2022 18:07:14.469] [main/FATAL] [net.minecraftforge.fml.ModLoader/]: Encountered non-modloading exceptions!
java.util.concurrent.CompletionException: java.lang.RuntimeException
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.RuntimeException
	at net.minecraftforge.fml.ModList.completableFutureFromExceptionList(ModList.java:139) ~[forge:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 9 more
	Suppressed: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
		at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.21.jar:36.2]
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
		at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListener(SpongeEventManager.java:280) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:310) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.handler$zpa000$forge$registerModForSpongeListeners(FMLModContainer.java:1056) ~[forge:36.2]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:97) ~[forge:36.2]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[14Jan.2022 18:07:14.475] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.util.concurrent.CompletionException: java.lang.RuntimeException
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.RuntimeException
	at net.minecraftforge.fml.ModList.completableFutureFromExceptionList(ModList.java:139) ~[forge:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 9 more
	Suppressed: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
		at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.21.jar:36.2]
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
		at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListener(SpongeEventManager.java:280) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:310) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.handler$zpa000$forge$registerModForSpongeListeners(FMLModContainer.java:1056) ~[forge:36.2]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:97) ~[forge:36.2]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

[debug.log](https://github.com/SpongePowered/Sponge/files/7873545/debug.log)

### PR DESCRIPTION
**Pull request by gabizou**
# The end of Reflection

The main goal of this PR is to eliminate usages of Java's Reflection API due to the intrinsic nature of Reflection being finicky with our lack of control over ClassLoaders. There are specific cases where classes may not be available and due to the nature of the JVM, it's acceptable for some classes to be missing since the exception will only be triggered by code path explicitly. This explicit access is normally triggered by compiled code, but can be implicitly triggered by Reflection.

## The Solution

Instead of triggering class loads by Reflection, we will instead use ASM ClassReaders to perform the work we need to do. In some cases, this is as simple as a ClassVisitor that analyzes the methods declared on the class. In other cases, it's finding any Listeners available on a Class.

Fixes #3589 #3597 #3574 #3548 #3532

### CODE REVIEW

File: src/main/java/org/spongepowered/common/event/manager/InvokeEventListenerFactory.java [hunk 1]
```diff
@@ -53,29 +51,29 @@ public AnnotatedEventListener create(Object handle, Method method) throws Except
...
-                    for (Object o : filtered) {
-                        args.append(o.getClass().getName()).append(" ");
-                    }
-                    this.method.invoke(this.handle, filtered);
-                }
-            } else {
-                this.method.invoke(this.handle, event);
-            }
+        public void handle(final Event event) throws Exception {
+//            if (this.filter != null) {
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/InvokeEventListenerFactory.java]: I don't think this can reasonably come back, maybe just delete this whole factory?

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 2]
```diff
@@ -0,0 +1,451 @@
...
+        return new ListenerMethodVisitor(this, name, descriptor, access, signature);
+    }
+
+    public List<DiscoveredMethod> foundListenerMethods() {
+        return Collections.unmodifiableList(this.foundListenerMethods);
+    }
+
+    static class ListenerMethodVisitor extends MethodVisitor {
+        private final ListenerClassVisitor classVisitor;
+        @MonotonicNonNull private DiscoveredMethod discoveredMethod;
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]:
```suggestion
        private @MonotonicNonNull DiscoveredMethod discoveredMethod;
```

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 3]
```diff
@@ -0,0 +1,451 @@
...
+
+        public ListenerMethodVisitor(
+            final ListenerClassVisitor listenerClassVisitor, final String name, final String descriptor,
+            final int access,
+            @Nullable final String signature
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]:
```suggestion
            final @Nullable String signature
```

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 4]
```diff
@@ -0,0 +1,451 @@
...
+        ) {
+            super(Opcodes.ASM9);
+            this.classVisitor = listenerClassVisitor;
+            final Type[] type = Type.getArgumentTypes(descriptor);
+            final ListenerParameter[] parameters = new ListenerParameter[type.length];
+            for (int i = 0; i < type.length; i++) {
+                parameters[i] = new ListenerParameter(this.discoveredMethod, type[i]);
+            }
+            // TODO - figure out a cleaner way to do this, this works for:
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]: maybe take a look at ASM's `SignatureReader`? it should be able to capture the applicable type, and Geantyref has methods to create a runtime reflection `Type` ourselves

**Review by zml2008 — CHANGES_REQUESTED** [review]

File: src/main/java/org/spongepowered/common/event/manager/InvokeEventListenerFactory.java (hunk 1 above)
Comment (gabizou) [reply src/main/java/org/spongepowered/common/event/manager/InvokeEventListenerFactory.java]: Having reviewed it in SF 1.12, it doesn't even seem to have been used even then. Deleting!

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java (hunk 4 above)
Comment (gabizou) [reply src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]: That's fair, I did read briefly about using SignatureReader, but didn't connect the dots on making it work (code written at 2am isn't always the sanest).

I did take advantage of Geantyref's TypeFactory in a few places already for creating `Type` instances as necessary.

Comment (gabizou) [reply src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]: Rewrote with SignatureVisitor on the parameter

File: src/main/java/org/spongepowered/common/event/filter/FilterGenerator.java [hunk 5]
```diff
@@ -168,52 +175,58 @@ public static FilterGenerator getInstance() {
...
+            final int[] plocals = new int[parameters.length - 1];
+            for (int i = 1; i < parameters.length; i++) {
+                final ListenerClassVisitor.ListenerParameter param = parameters[i];
                 ParameterFilterSourceDelegate source = null;
-                List<ParameterFilterDelegate> paramFilters = new ArrayList<>();
-                for (Annotation anno : param.getAnnotations()) {
-                    Object obj = FilterGenerator.filterFromAnnotation(anno.annotationType());
+                final List<ParameterFilterDelegate> paramFilters = new ArrayList<>();
+                for (final ListenerClassVisitor.ListenerAnnotation anno : param.annotations()) {
+                    final Object obj = FilterGenerator.filterFromAnnotation(Class.forName(anno.type().getClassName()));
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/filter/FilterGenerator.java]: This should probably use `method.declaringClass().getClassLoader()` to look up the annotation class name

File: src/main/java/org/spongepowered/common/event/filter/delegate/GetValueFilterSourceDelegate.java [hunk 6]
```diff
@@ -94,16 +93,16 @@ public GetValueFilterSourceDelegate(final GetValue anno) {
         final Label failure = new Label();
         // for all parameters p' before `param` that inherit from ValueContainer, excluding the event itself
         for (int i = paramIdx - 1; i > 0; --i) {
-            final Parameter param = params[i];
-            if (!ValueContainer.class.isAssignableFrom(param.getType())) {
+            final ListenerClassVisitor.ListenerParameter param = params[i];
+            if (!ValueContainer.class.isAssignableFrom(Class.forName(param.type().getClassName()))) {
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/filter/delegate/GetValueFilterSourceDelegate.java]: should use the declaring class's class loader for this as well

File: src/main/java/org/spongepowered/common/event/filter/delegate/GetterFilterSourceDelegate.java [hunk 7]
```diff
@@ -44,31 +44,32 @@
...
-        ClassWriter cw, MethodVisitor mv, Method method, int paramIdx, int local, final int[] plocals, final Parameter[] params
-    ) {
-        Class<?> targetType = params[paramIdx].getType();
-        Class<?> eventClass = params[0].getType();
-        String targetMethod = this.anno.value();
+        final ClassWriter cw, final MethodVisitor mv, final ListenerClassVisitor.DiscoveredMethod method,
+        final int paramIdx, int local, final int[] plocals, final ListenerClassVisitor.ListenerParameter[] params
+    ) throws ClassNotFoundException {
+        final Class<?> targetType = Class.forName(params[paramIdx].type().getClassName());
+        final Class<?> eventClass = Class.forName(params[0].type().getClassName());
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/filter/delegate/GetterFilterSourceDelegate.java]: declaring class's loader, just in case that's different

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 8]
```diff
@@ -0,0 +1,452 @@
...
+        @MonotonicNonNull String name;
+
+        ListenerParameter(final DiscoveredMethod method, final Type type) {
+            this.method = method;
+            this.type = type;
+            this.annotations = new LinkedList<>();
+        }
+
+        public Class<?> clazz() throws ClassNotFoundException {
+            return Class.forName(this.type.getClassName());
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]: should use method's declaring class

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 9]
```diff
@@ -0,0 +1,452 @@
...
+        }
+
+        @Override
+        public int hashCode() {
+            return Objects.hash(method, type, annotations);
+        }
+
+        public java.lang.reflect.Type genericType() throws ClassNotFoundException {
+            if (this.genericType == null) {
+                return TypeFactory.parameterizedClass(Class.forName(this.type.getClassName()));
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]: this.clazz()

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 10]
```diff
@@ -0,0 +1,452 @@
...
+            }
+            final java.lang.reflect.Type generic = TypeFactory.parameterizedClass(Class.forName(this.genericType.getClassName()));
+            return TypeFactory.parameterizedClass(Class.forName(this.type.getClassName()), generic);
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]: this.clazz()

File: src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java [hunk 11]
```diff
@@ -0,0 +1,452 @@
...
+
+        public Type type() {
+            return this.type;
+        }
+
+        public void put(final String name, final Object value) throws ClassNotFoundException,
+            AnnotationFormatException {
+            this.values.put(name, value);
+            this.annotation = TypeFactory.annotation(
+                (Class<? extends Annotation>) Class.forName(type.getClassName()), this.values);
```
Comment (zml2008) [inline src/main/java/org/spongepowered/common/event/manager/ListenerClassVisitor.java]: need to pas the declaring class's classloader through here

**Review by zml2008 — CHANGES_REQUESTED** [review]
