### PR TITLE
Fix incorrect command permission checks in some situations.

### LINKED ISSUE #1243: minecraft:command calls plugin permissions
Issue is described here in more detail
https://github.com/NucleusPowered/Nucleus/issues/739

, but short story:
Install Nucleus (or probably any other plugin that overrides vanilla mc commands)
Give user `nucleus.time.base` perm
Player should be ONLY have perms to do `/time` to get the time (no perms to change it)
Use `/minecraft:time set xx`
Output:
server changes time
Permission called `nucleus.time.base`

What should happen: You should get a no permission message

Setup: 
Nucleus 25.1
SF 1.10.2 2223
Luckperms 2.17.71

### PR DESCRIPTION
**Pull request by dualspiral**
When a Sponge plugin command takes a command alias that either Vanilla Minecraft or a Forge mod tries to take later, any permission checks on for the vanilla/mod command are directed to the Sponge plugin's command instead. This commit fixes this by:

* Adding updateNamespacedAlias(String ownerId) method to the CommandBase (via `IMixinCommandBase`), which is called on instantiation of `MinecraftCommandWrapper` (and, by inheritance, `ForgeMinecraftCommandWrapper` in SF), prefixing the output of `getName()` with the owning plugin's ID followed by a colon.
* Injecting into the checkPermission call to use this namespaced alias, if it exists.

This then ensures that the permission check goes to the correct alias. I've opted to do it this way, rather than just change the `MinecraftCommandWrapper`, in case something calls `CommandBase#checkPermission` directly.

As an aside, I did want to use a `@Redirect` on `this.getName()`, but I couldn't get it to work. [I tried this](https://gist.github.com/dualspiral/bea485e2382e0c5e4d47c3e6e0786283), if someone would rather have a redirect and can point out what I've done wrong - I'll update it. Note that `Lnet/minecraft/command/CommandBase;getName()Ljava/lang/String;` matches what I get when I look at the bytecode...

**Test Plugin:** [something like this should suffice](https://gist.github.com/dualspiral/103cfe174610e0de4fe940f6368f1efd). Run `/tp` and `/minecraft:tp`. You should only get the permission check message for `/tp`, but unpatched, you get the permission check message for `/minecraft:tp` too. Patched, you do not.

This fixes #1243

### CODE REVIEW

**Comment by stephan-gh** [comment]
The `@Redirect` you posted works fine for me: https://gist.github.com/Minecrell/6659c542f8ecc4de60dfdca7b814574b#file-java-L104-L106

**Comment by dualspiral** [comment]
Huh, interesting. I kept getting this: https://gist.github.com/dualspiral/f89650348912b3d73f7f7a731aa59922

**Comment by stephan-gh** [comment]
@dualspiral Can you try again? I used [this mixin](https://gist.github.com/Minecrell/03879edeb8cd1256058a223a96cb742a) and it seems to work fine.

Edit: Nevermind, seems to be a bug in the Mixin annotation processor. The injection isn't re-obfuscated properly.

**Comment by dualspiral** [comment]
@Minecrell Ahh, right! Glad I'm not going mad. I can update this PR if you like, pending any changes to the AP.

I imagine that you know what the issue is now anyway, but if it makes any difference, I'm using IntelliJ.

**Comment by stephan-gh** [comment]
@dualspiral The injection should work if you run in IntelliJ IDEA directly (in the dev environment). It will only fail in production.

**Comment by dualspiral** [comment]
Right, I see, I tend to just build a production jar because I don't open up SF/SV in my IDE that often and... well, haven't set it up as a dev environment yet.

Let me know if/when you want me to revisit anything on this PR. I'll leave it like this for the moment unless you want me to change it now.

File: src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java [hunk 1]
```diff
@@ -43,4 +55,15 @@ public void setExpandedSelector(boolean expandedSelector) {
...
+        this.namespacedAlias = ownerId + ":" + this.getName();
+    }
+
+    @Inject(method = "checkPermission", at = @At("HEAD"), cancellable = true)
+    public void onCheckPermission(MinecraftServer server, ICommandSender commandSender, CallbackInfoReturnable<Boolean> cir) {
+        if (this.namespacedAlias != null) {
+            cir.setReturnValue(commandSender.canUseCommand(this.getRequiredPermissionLevel(), this.namespacedAlias));
+        }
+    }
 }
```
Comment (liach) [inline src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java]: Needs a new line.

File: src/main/java/org/spongepowered/common/interfaces/command/IMixinCommandBase.java [hunk 2]
```diff
@@ -30,4 +30,5 @@
 
     void setExpandedSelector(boolean expandedSelector);
 
+    void updateNamespacedAlias(String ownerId);
 }
```
Comment (liach) [inline src/main/java/org/spongepowered/common/interfaces/command/IMixinCommandBase.java]: Needs a new line.

File: src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java [hunk 3]
```diff
@@ -43,4 +55,15 @@ public void setExpandedSelector(boolean expandedSelector) {
...
 
+    @Override
+    public void updateNamespacedAlias(String ownerId) {
+        this.namespacedAlias = ownerId + ":" + this.getName();
+    }
+
+    @Inject(method = "checkPermission", at = @At("HEAD"), cancellable = true)
+    public void onCheckPermission(MinecraftServer server, ICommandSender commandSender, CallbackInfoReturnable<Boolean> cir) {
+        if (this.namespacedAlias != null) {
+            cir.setReturnValue(commandSender.canUseCommand(this.getRequiredPermissionLevel(), this.namespacedAlias));
```
Comment (liach) [inline src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java]: You don't really need `this` for instance method calls.

File: src/main/java/org/spongepowered/common/command/MinecraftCommandWrapper.java [hunk 4]
```diff
@@ -81,6 +82,11 @@
     public MinecraftCommandWrapper(final PluginContainer owner, final ICommand command) {
         this.owner = owner;
         this.command = command;
+
+        // Add the namespaced alias to the wrapped command so permission checks are sent to the right command.
+        if (this.command instanceof IMixinCommandBase) {
+            ((IMixinCommandBase)this.command).updateNamespacedAlias(this.owner.getId());
```
Comment (liach) [inline src/main/java/org/spongepowered/common/command/MinecraftCommandWrapper.java]:
```java
((IMixinCommandBase) this.command).updateNamespacedAlias(this.owner.getId());
```
Spacing?

**Comment by stephan-gh** [comment]
@dualspiral Please try using a `@Redirect` now (after a Gradle refresh). It should be fixed in https://github.com/SpongePowered/Mixin/commit/4b7b5a05f4b155e99502dce250ee77a9f7a658b0

**Comment by dualspiral** [comment]
@Minecrell Will do once I'm home from work, thanks for letting me know.

**Comment by dualspiral** [comment]
@Minecrell Yep, this works fine now, thanks.

The patch has been tested on API 6, but should work on API 5.2 too.

File: src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java [hunk 5]
```diff
@@ -43,4 +50,15 @@ public void setExpandedSelector(boolean expandedSelector) {
         this.expandedSelector = expandedSelector;
     }
 
+    @Override
+    public void updateNamespacedAlias(String ownerId) {
+        this.namespacedAlias = ownerId + ":" + getName();
+    }
+
+    @Redirect(method = "checkPermission(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/command/ICommandSender;)Z",
```
Comment (stephan-gh) [inline src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java]: Is the full method descriptor necessary here? Usually you can omit the `(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/command/ICommandSender;)Z` if only one method with the same name exists in the target class (which is the case here I think?).

Comment (dualspiral) [reply src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java]: Yeah, fair point. I did this whilst trying to get it to work before, didn't think about it after. Will test and then commit.

Comment (dualspiral) [reply src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBase.java]: @Minecrell Yep, you were right - works. Updated.

**Review by stephan-gh — APPROVED** [review]

**Comment by kashike** [comment]
Thanks.

**Comment by dualspiral** [comment]
Is there a possiblity of getting this in `stable-5` too? #1243 was reported from a 1.10.2 server.

I can recreate this as a PR for 1.10.2 too if you want - note that it will require bumping the Mixins dep to 0.6.8-SNAPSHOT too.

**Comment by kashike** [comment]
PR welcome! :smile_cat:

**Comment by dualspiral** [comment]
Will do tomorrow then!

**Comment by dualspiral** [comment]
#1262
