### PR TITLE
Fix/configtranslator

### LINKED ISSUE #1598: ParticleOptions of a ParticleEffect not being deserialized from a config file
**I am currently running...**

- SpongeForge version: not tested
- SpongeVanilla version: spongevanilla-1.11.2-6.1.0-BETA-0
- Java version: 1.8.0_121
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: None

**What is the expected result?**
ParticleEffect deserialized from a config file contaning both the ParticleType and the various ParticleOptions contained in the config.

**What is the current result?**
The ParticleEffect when deserialized loads only the ParticleType from the config, skipping entirely the ParticleOptions, even if actually in the config file.

**Further testing**
I made test plugin to save a ParticleEffect into a config file using Hocon and a ConfigurationNode.
I created the ConfigurationLoader and saved the ParticleEffect like this:
```java
ConfigurationLoader<CommentedConfigurationNode> config = LoaderHoconConfigurationLoader.builder().setPath(defaultConfigPath).build();
CommentedConfigurationNode rootNode = this.configLoader.load();

this.particle = ParticleEffect.builder()
                .type(ParticleTypes.CLOUD)
                .offset(new Vector3d(5d, 5d, 5d))
                .velocity(new Vector3d(0.5d, 0.5d, 0.5d))
                .build();

rootNode.setValue(TypeToken.of(ParticleEffect.class), this.particle);

this.configLoader.save(rootNode);

System.out.println("Created particle: " + particleEffectToString(this.particle));

private String particleEffectToString(ParticleEffect particleEffect) {
        StringBuilder string = new StringBuilder();

        string.append(particleEffect.getType());
        string.append(" options (" + particleEffect.getOptions().size() + "): ");
        particleEffect.getOptions().forEach((particleOption, o) -> {
            string.append(particleOption.getName());
            string.append(particleOption.getValueType());
        });

        return string.toString();
}
```
The println output is this
```
Created particle: SpongeParticleType{id=minecraft:cloud, name=cloud, internalType=CLOUD} options (2): offsetclass com.flowpowered.math.vector.Vector3dvelocityclass com.flowpowered.math.vector.Vector3d
```
The resulting config file is this:
```
Options=[
    {
        Option="minecraft:offset"
        Value {
            x=5.0
            y=5.0
            z=5.0
        }
    },
    {
        Option="minecraft:velocity"
        Value {
            x=0.5
            y=0.5
            z=0.5
        }
    }
]
Type="minecraft:cloud"
```
Now when I load the ParticleEffect at next execution from the config file like this:
```java
ParticleEffect particle = rootNode.getValue(TypeToken.of(ParticleEffect.class));

System.out.println("Loaded particle: " + particleEffectToString(this.particle));
```
The ParticleTypes is assigned but there are no ParticleOptions, as you can see from the println output:
```
Loaded particle: SpongeParticleType{id=minecraft:cloud, name=cloud, internalType=CLOUD} options (0): 
```
Gist containing both the logs at first and second execution and the test plugin main class [here](https://gist.github.com/anthonysan95/48a198b4cb2fad499976d07c810aab93).

If I did something wrong please tell me.. I tried in every possible way to deserialize it properly.
I even tried to go into the SpongeParticleEffectBuilder to see if the problem was there and this is what I found:
https://github.com/SpongePowered/SpongeCommon/blob/a5618c7a8bd32a10102fc443be8b0bc65002e511/src/main/java/org/spongepowered/common/effect/particle/SpongeParticleEffectBuilder.java#L64
I tested putting two println one before the line to see if the container contains the PARTICLE_OPTIONS and one inside the foreach printing the view, results: the first prints true while the other doesn't get called but I couldn't manage to get why.

### LINKED ISSUE #1963: `ConfigurateTranslator.translateMapOrList` throws NPE
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-74
  
`ConfigurateTranslator.translateMapOrList` throws NPE if node doesn't contain `key`.
Here is check if `key` is `null`: 
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/data/persistence/ConfigurateTranslator.java#L123-L124
But inside this method there is `node.getKey().XXX` calls.
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/data/persistence/ConfigurateTranslator.java#L83

So it throws NPE for me:
```
java.lang.NullPointerException: null
	at org.spongepowered.common.data.persistence.ConfigurateTranslator.translateMapOrList(ConfigurateTranslator.java:83) ~[ConfigurateTranslator.class:1.12.2-7.1.0-BETA-74]
	at org.spongepowered.common.data.persistence.ConfigurateTranslator.addTo(ConfigurateTranslator.java:124) ~[ConfigurateTranslator.class:1.12.2-7.1.0-BETA-74]
	at org.spongepowered.common.data.persistence.ConfigurateTranslator.translateFromNode(ConfigurateTranslator.java:71) ~[ConfigurateTranslator.class:1.12.2-7.1.0-BETA-74]
	at org.spongepowered.common.data.persistence.ConfigurateTranslator.translate(ConfigurateTranslator.java:115) ~[ConfigurateTranslator.class:1.12.2-7.1.0-BETA-74]
	at org.spongepowered.common.data.persistence.ConfigurateTranslator.translate(ConfigurateTranslator.java:45) ~[ConfigurateTranslator.class:1.12.2-7.1.0-BETA-74]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:50) ~[DataSerializableTypeSerializer.class:1.12.2-7.1.0-BETA-74]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:41) ~[DataSerializableTypeSerializer.class:1.12.2-7.1.0-BETA-74]
```

@gabizou

### PR DESCRIPTION
**Pull request by ImMorpheus**
Fix https://github.com/SpongePowered/SpongeCommon/issues/1963
Fix https://github.com/SpongePowered/SpongeCommon/issues/1598
Fix x.0 being deserialized as int 

This does solve https://github.com/SpongePowered/SpongeAPI/issues/1543, however it still doesn't solve the type information loss mentioned in that issue. 

We need to keep in mind that `DataFormats.HOCON` and `DataFormats.JSON` SHOULD return the same DataView when serializing object.
Right now, HOCON is broken (see related issues mentioned above)

### CODE REVIEW

File: src/main/java/org/spongepowered/common/data/persistence/JsonDataFormat.java [hunk 1]
```diff
@@ -144,18 +144,20 @@ private static Object read(JsonReader reader) throws IOException {
...
-        int nextInt = (int) nextDouble;
-        if (nextInt == nextDouble) {
-            return nextInt;
-        }
-
-        long nextLong = (long) nextDouble;
-        if (nextLong == nextDouble) {
-            return nextLong;
+        String str = reader.nextString();
+        try {
```
Comment (dualspiral) [inline src/main/java/org/spongepowered/common/data/persistence/JsonDataFormat.java]: Throwing exceptions (or allowing them to be thrown) is a rather expensive operation. Instead, maybe we could do a check to see if a decimal point exists in the string and parse a double based on that instead, though I don't know if that would be faster.

It would neaten this up slightly too.

**Comment by randombyte-developer** [comment]
Does this fix #2094? Seems to be the same issue, but nothing linked to that issue as of now.

**Comment by ImMorpheus** [comment]
> Does this fix #2094? Seems to be the same issue, but nothing linked to that issue as of now.

Likely. You can try use JSON and compare the DataContainers.
