### PR TITLE
Fix login plugin messages & IP forwarding

### LINKED ISSUE #3905: IP-forwarding completely broken (both legacy & modern) on 1.20.2
### Affected Product(s)

SpongeVanilla

### Version

1.20.2-11.0.0-RC1386

### Operating System

Linux

### Java Version

17.0.8.1/64-bit

### Plugins/Mods

```shell
-
```

### Describe the bug

IP-forwarding appears to be completely unusable on API-11. This is presumably due to the introduction of the configuration phase. The following exceptions are thrown when a player attempts to join to server when using it.

Legacy forwarding: https://gist.github.com/avaruus1/a23767136a1df965f9fcd18bd5b3f279

Modern: https://gist.github.com/avaruus1/f914cebbfdbc6dbe25fecce0042db2a7

### Link to logs

_No response_

### PR DESCRIPTION
**Pull request by avaruus1**
Fixes both legacy & modern ip forwarding and login plugin messages.

Resolves #3905

### CODE REVIEW

File: src/main/java/org/spongepowered/common/network/channel/SpongeChannelManager.java [hunk 1]
```diff
@@ -386,8 +386,16 @@ public void handleLoginResponsePayload(final EngineConnection connection, final
...
+        final ChannelBuf payload;
+
+        if (packet.payload() != null) {
+            payload = this.bufferAllocator.buffer();
+            packet.payload().write((FriendlyByteBuf) payload);
+        }
+
+        else {
+            payload = null;
+        }
```
Comment (aromaa) [inline src/main/java/org/spongepowered/common/network/channel/SpongeChannelManager.java]:
```suggestion

        final ChannelBuf payload;
        if (packet.payload() != null) {
            payload = this.bufferAllocator.buffer();
            packet.payload().write((FriendlyByteBuf) payload);
        } else {
            payload = null;
        }
```

File: src/mixins/java/org/spongepowered/common/mixin/core/network/protocol/login/ServerboundCustomQueryAnswerPacketMixin.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+import net.minecraft.network.FriendlyByteBuf;
+import net.minecraft.network.protocol.login.ServerboundCustomQueryAnswerPacket;
+import net.minecraft.network.protocol.login.custom.CustomQueryAnswerPayload;
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.injection.At;
+import org.spongepowered.asm.mixin.injection.Inject;
+import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;
+
+@Mixin(ServerboundCustomQueryAnswerPacket.class)
+public class ServerboundCustomQueryAnswerPacketMixin {
```
Comment (aromaa) [inline src/mixins/java/org/spongepowered/common/mixin/core/network/protocol/login/ServerboundCustomQueryAnswerPacketMixin.java]:
```suggestion
public abstract class ServerboundCustomQueryAnswerPacketMixin {
```

File: src/mixins/java/org/spongepowered/common/mixin/core/network/protocol/login/ServerboundCustomQueryAnswerPacketMixin.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+
+    @Inject(method = "readUnknownPayload", at = @At(value = "INVOKE", target = "Lnet/minecraft/network/FriendlyByteBuf;skipBytes(I)Lnet/minecraft/network/FriendlyByteBuf;"), cancellable = true)
+    private static void readUnknownPayload(final FriendlyByteBuf $$0, final CallbackInfoReturnable<CustomQueryAnswerPayload> cir) {
```
Comment (aromaa) [inline src/mixins/java/org/spongepowered/common/mixin/core/network/protocol/login/ServerboundCustomQueryAnswerPacketMixin.java]:
```suggestion
    private static void impl$onReadUnknownPayload(final FriendlyByteBuf $$0, final CallbackInfoReturnable<CustomQueryAnswerPayload> cir) {
```

File: src/mixins/resources/mixins.sponge.core.json [hunk 4]
```diff
@@ -241,7 +241,8 @@
         "world.scores.ScoreMixin",
         "world.ticks.LevelTicksMixin",
         "world.ticks.ScheduledTickMixin",
-        "world.item.crafting.SmithingTransformRecipeMixin"
+        "world.item.crafting.SmithingTransformRecipeMixin",
+        "network.protocol.login.ServerboundCustomQueryAnswerPacketMixin"
```
Comment (aromaa) [inline src/mixins/resources/mixins.sponge.core.json]: Keep the mixins in alphabetic order.

**Review by aromaa — CHANGES_REQUESTED** [review]
LGTM. Few NITs.

**Review by aromaa — APPROVED** [review]
Thank you!!
